### ISSUE TITLE
Does this client support Service Accounts?

### ISSUE THREAD

**Issue by sjordan1975** [rapidwebltd/php-google-contacts-v3-api#29] opened 2017-01-09 10:11 UTC
From the Google Documentation:

> If you have a Google Apps domain—if you use Google Apps for Work, for example—an administrator of the Google Apps domain can authorize an application to access user data on behalf of users in the Google Apps domain. For example, an application that uses the Google Calendar API to add events to the calendars of all users in a Google Apps domain would use a service account to access the Google Calendar API on behalf of users. Authorizing a service account to access data on behalf of users in a domain is sometimes referred to as "delegating domain-wide authority" to a service account.

See https://developers.google.com/api-client-library/php/auth/service-accounts

**Comment by DivineOmega** [comment] 2017-01-09 13:05
I've actually not had the ability to test with a Google Apps service account.

This may work if you're able to complete the oauth process with the account. Please feel free to download the client and try it out. I'll be happy to help out where I can.

**Comment by sjordan1975** [comment] 2017-01-09 13:17
Thank you. Will try it out.

**Comment by DivineOmega** [comment] 2017-05-02 10:15
I'm closing this issue as a duplicate of #8. Further discussion regarding service accounts should go in that issue.

**Closed by DivineOmega** 2017-05-02 10:15 UTC
