### ISSUE TITLE
Showing Fatal error: Uncaught exception 'Google_IO_Exception' with message '<url> malformed'

### ISSUE THREAD

**Issue by shashankkumrawat** [rapidwebltd/php-google-contacts-v3-api#16] opened 2016-05-21 11:40 UTC
I get following error if I open **"test_individual.php"** in web browser-

**Fatal error: Uncaught exception 'Google_IO_Exception' with message '<url> malformed' in /home/cityretails/public_html/testing/3/vendor/google/apiclient/src/Google/IO/Curl.php:126 Stack trace: #0 /home/cityretails/public_html/testing/3/vendor/google/apiclient/src/Google/IO/Abstract.php(136): Google_IO_Curl->executeRequest(Object(Google_Http_Request)) #1 /home/cityretails/public_html/testing/3/vendor/google/apiclient/src/Google/Auth/OAuth2.php(77): Google_IO_Abstract->makeRequest(Object(Google_Http_Request)) #2 /home/cityretails/public_html/testing/3/factories/ContactFactory.php(79): Google_Auth_OAuth2->authenticatedRequest(Object(Google_Http_Request)) #3 /home/cityretails/public_html/testing/3/test_individual.php(12): rapidweb\googlecontacts\factories\ContactFactory::getBySelfURL('...') #4 {main} thrown in /home/cityretails/public_html/testing/3/vendor/google/apiclient/src/Google/IO/Curl.php on line 126**

I don't know whats going wrong there while I have setup everything correctly.

**Comment by KaisNeffati** [comment] 2016-05-23 20:42
Hello , i'm facing this problem, what can i do please?
Fatal error: Uncaught exception 'Exception' with message 'No selfURL specified.' in C:\xampp\htdocs\projects\New folder (2)\vendor\rapidwebltd\php-google-contacts-v3-api\test_individual.php:8 Stack trace: #0 {main} thrown in C:\xampp\htdocs\projects\New folder (2)\vendor\rapidwebltd\php-google-contacts-v3-api\test_individual.php on line 8

**Comment by DivineOmega** [comment] 2016-05-24 08:40
Hi there. Does `test.php` give you the same problem?

**Comment by KaisNeffati** [comment] 2016-05-24 10:13
Thank you for responding, I think that there is something missed in the app, I do all the configuration said in the manual, but I can't get any data: test.php indicate this: No contacts retrieved! .

**Comment by DivineOmega** [comment] 2016-05-24 12:52
Okay, this seems like the same issue described in #14. I'll try to replicate this issue and find out what the problem is.

**Comment by KaisNeffati** [comment] 2016-05-24 13:29
You are making a very good job, nice work,please if you find a solution let me know 
Thinks

**Comment by DivineOmega** [comment] 2017-05-02 10:19
I'm going to close this as a duplicate of #14. If you are still experiencing this issue, please add additional information there.

**Closed by DivineOmega** 2017-05-02 10:19 UTC
